// Auto-generated by javascript_version.py
export const DATETIME_STR = "2024-08-27 12:08:17";
export const VERSION_DATETIME = new Date(DATETIME_STR);
export const VERSION_STR = "v" + DATETIME_STR.replace(/[-: ]/g, "");

const VERSION = { DATETIME_STR, VERSION_DATETIME, VERSION_STR };
export default VERSION;
