// Auto-generated by javascript_version.py
export const DATETIME_STR = "2024-08-27 11:37:06";
export const VERSION_DATETIME = new Date(DATETIME_STR);

const VERSION = { DATETIME_STR, VERSION_DATETIME };
export default VERSION;
